### ISSUE TITLE
@media max-width , 화면이 클 때 과목 분할하기

### ISSUE THREAD

**Issue by 00-FF** [0verfl0w767/Lecture-Timetable#4]
# flex
```css
course-items {
    display: flex;
    flex-wrap: wrap;
    flex-direction: row;
    justify-content: center;
    ...
}

course-item {
    width: calc(100% / 4);
    ...
}
```

# grid (이 방법을 택함)

위에 flex에서는 만약 홀수로 남겨졌을 때 가운데 정렬 기준으로 요상하게 된다.

```css
course-items {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    padding: 0 50px; 
    gap: 5px;
}
```

# before

![Image](https://github.com/user-attachments/assets/e61a8799-2952-4a47-88d6-abc88ee692a8)

# after

![Image](https://github.com/user-attachments/assets/8b485c59-5bf9-4b5c-8136-d7ea8151a787)

화면이 큰 경우에는 공간이 허전한 감이 있으니 수정을 좀 해줍시다..?

**Comment by 00-FF** [comment]
- 650 <= Medium <= 1099

- 1100 <= Large

```css
<style>
    @media (min-width: 1100px) { /* Large */
      .course-items {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        padding: 0 40px; 
        gap: 5px;
      }
      
      .course-item {
        font-size: 1.2rem;
      }
    }

    @media (min-width: 650px) and (max-width: 1099px) { /* Medium */
      .course-items {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        padding: 0 20px; 
        gap: 5px;
      }
      
      .course-item {
        font-size: 1.1rem;
      }
    }
</style>
```
